[package]
name = "trailsbuddy-backend-rust"
version = "0.1.0"
edition = "2021"
authors = ["Sibaprasad Maiti<sibu.it13@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.6.4"
hyper = {version = "0.14", features = ["full"]}
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.3.5", features = ["full"] }
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
dotenvy = "0.15.6"