[package]
name = "trailsbuddy-backend-rust"
version = "0.1.0"
edition = "2021"
authors = ["Sibaprasad Maiti<sibu.it13@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.6.4"
serde = { version = "1.0", features = ["derive"] } 
tracing-subscriber = "0.3"
tracing = "0.1"
dotenvy = "0.15.6"